- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.7
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, jupyter ]
      args: [--fix, --exit-non-zero-on-fix, --show-fixes]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, jupyter ]
